//semantic error: redeclare a variable in the same scope
package fault2
func main(){
	x int=0
	x string="something"
}
